= Quarkus image:logo.svg[width=25em] Web Bundler - Advanced Guides

include::./includes/attributes.adoc[]

== Web Root

The Web Root is `src/main/resources/web`, this is where the Web Bundler will look for stuff to bundle and serve.

[#static]
== Static files

Files in `src/main/resources/web/static/&#42;&#42;` will be served statically under http://localhost:8080/static/ (you can choose another directory name xref:config-reference.adoc#quarkus-web-bundler_quarkus.web-bundler.static[Config Reference])

== Bundling

=== Presets

The Web Bundler is pre-configured with presets to make it easy to use out of the box.

[#preset-app]
==== App

Directory `src/main/resources/web/app` is destined to contain the scripts, styles and possibly assets for your app. It will be bundled and served into `/static/bundle/main-[hash].[ext].` (see <<entry-points>> for more options)

[#server-side-web-components]
==== Server Side Web Components (Qute)

This is not always needed but if you need to add specific script and/or style to your {quarkus-guides-url}/qute-reference#user_tags[Qute tags] (Server Side Web Components). This preset will help you do it elegantly.

By convention, your component will be defined in `src/main/resources/web/components/[name]/[name].&#42;`. The scripts, styles and assets will be bundled, the html template will be usable as a {quarkus-guides-url}/qute-reference#user_tags[Qute tag].

This way all your components scripts/styles will be bundled and you tags will be available in your templates.

=== Importing Web Dependencies

Once added in the pom.xml, the web dependencies can be imported and used with the ES import syntax, they will automatically be bundled.

NOTE: Currently Web Dependencies need to be imported in order to be bundled.

.web/app/script.js
[source,javascript]
----
import $ from 'jquery';
import 'bootstrap/dist/css/bootstrap.css';

$('.hello').innerText('Hello');
----

Styles can be also be imported from a scss file:

.web/app/style.scss
[source,scss]
----
@import "bootstrap/dist/css/bootstrap.css";
----

WARNING: It is currently not possible to import `scss` from the dependencies (https://github.com/quarkiverse/quarkus-web-bundler/issues/58[more info]).

[#what-is-bundled]
=== What is bundled

[#indexing]
==== Indexing

Only what's imported will be part of the resulting bundle, to make it easy, the Web Bundler will automatically generate an index importing all the files found in an entry-point directory.

Of course, you can also provide this index manually (named `index.js,ts,jsx,tsx`) and choose what to import. Example:

.src/main/resources/web/app/index.js
[source,javascript]
----
import './my-script.js'
import './my-style.scss'
import './example.png'
----

[#entry-points]
==== Entry-Points

You may also configure other entry-points:

.src/main/resources/application.properties
[source,properties]
----
quarkus.web-bundler.bundle.foo=true // <1>
quarkus.web-bundler.bundle.bar=true // <2>
quarkus.web-bundler.bundle.bar.key=my-key
quarkus.web-bundler.bundle.bar.dir=my-dir

----
<1> Bundle `src/main/resources/web/foo/...` into `/static/bundle/foo-[hash].[ext]`
<2> Bundle `src/main/resources/web/my-dir/...` into `/static/bundle/my-key-[hash].[ext]`

or

.src/main/resources/application.properties
[source,properties]
----
quarkus.web-bundler.bundle.page-1=true // <1>
quarkus.web-bundler.bundle.page-2=true // <2>
----
<1> Bundle `src/main/resources/web/page-1/...`
<2> Bundle `src/main/resources/web/page-2/...`

NOTE: As soon as more than one entry-point key is configured, shared code and web dependencies are split off into a separate file. That way if the user first browses to one page and then to another page, they don't have to download all the JavaScript for the second page from scratch if the shared part has already been downloaded and cached by their browser. The path of the shared static script is `/static/bundle/chunk-[hash].js`.

This is perfect if you create an app with different pages using different scripts, libraries and styles.

You may also split the bundle for the `app` and the `component` presets (by default they will be bundled together in `main`):
.application.properties
[source,properties]
----
quarkus.web-bundler.presets.app.key=app // <1>
quarkus.web-bundler.presets.components.key=components // <2>
----
<1> The app will be bundled in `/static/bundle/app-[hash].js`
<2> The components will be bundled in `/static/bundle/components-[hash].js`


[#loaders]
=== How is it bundled (Loaders)

Depending on the app file extensions the Web Bundler will use xref:config-reference.adoc#quarkus-web-bundler_quarkus.web-bundler.loaders.js[pre-configured loaders] to bundle the app.

By default, you can import and use fonts and images from your scripts and styles (svg, gif, png, jpg, ...) using their relative path, they will be automatically copied and served using the xref:config-reference.adoc#quarkus-web-bundler_quarkus.web-bundler.loaders.file[file loader].

In a css file, using `url('./example.png')` will be processed by a loader (see xref:config-reference.adoc#quarkus-web-bundler_quarkus.web-bundler.loaders.file[file loader]), the file will be copied with a static name and the path will be replaced by the new file static path (e.g. `/static/bundle/assets/example-QH383.png`).

NOTE: For convenience, when using a static file (e.g. `url('/static/example.png')`, the path will not be processed because all files under `/static/&#42;&#42;` are marked as external (to be ignored from the bundling). Since `/static/example.png` will be served (See <<static>>), it is ok.


=== SCSS, SASS

You can use scss or sass files out of the box. Local import are supported. Importing partials is also supported begin with `_` (as in `_code.scss` imported with `@import 'code';`).

WARNING: It is currently not possible to import `scss` from the dependencies (https://github.com/quarkiverse/quarkus-web-bundler/issues/58[more info]).

[#web-dependencies]
== Web Dependencies

The Web Bundler is integrated with NPM dependencies through <<mvnpm>> (default) or <<webjars>>.
Once added in the pom.xml the dependencies are directly available through import from the scripts and styles.

[#mvnpm]
=== MVNPM (default)

mvnpm (Maven NPM) is a maven repository facade on top of the NPM Registry.

Lookup for packages on https://mvnpm.org or https://www.npmjs.com/ then add them as web dependencies to your pom.xml:

.pom.xml
[source,xml]
----
...
<dependencies>
    ...
    <dependency>
        <groupId>org.mvnpm</groupId> // <1>
        <artifactId>jquery</artifactId> // <2>
        <version>3.7.0</version> // <3>
    </dependency>
</dependencies>
...
----

<1> use `org.mvnpm` or `org.mvnpm.at.something` for `@something/dep`
<2> All dependencies published on NPM are available
<3> Any https://www.npmjs.com/package/jquery?activeTab=versions[published NPM version] for your dependency

If a package or a version in not yet available in Maven Central:
- [Available Soon] You can also use the mvnpm.org website to synchronize new versions with Maven Central.
- If configured with the mvnpm repository, when requesting a dependency, it will inspect the registry to see if it exists and if it does, convert it to a Maven dependency and publish it to Maven Central so that future developers won't need the repository.

.settings.xml
----
<settings>
    <profiles>
        <profile>
            <id>mvnpm</id>
            <repositories>
                <repository>
                    <id>central</id>
                    <name>central</name>
                    <url>https://repo.maven.apache.org/maven2</url>
                </repository>
                <repository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>mvnpm.org</id> 
                    <name>mvnpm</name>
                    <url>https://repo.mvnpm.org/maven2</url>
                </repository>
            </repositories>
        </profile>
    </profiles>

    <activeProfiles>
        <activeProfile>mvnpm</activeProfile>
    </activeProfiles>

</settings>
----

[#webjars]
=== WebJars

NOTE: Adding new dependencies or recent versions has to be done manually from their website.

WebJars are client-side web libraries (e.g. jQuery & Bootstrap) packaged into JAR (Java Archive) files. You can browse the repository from https://www.webjars.org/[the website, window="_blank"].

.application.properties
[source,properties]
----
quarkus.web-bundler.dependencies.type=webjars
----

.pom.xml
[source,xml]
----
<dependency>
    <groupId>org.webjars.npm</groupId>
    <artifactId>jquery</artifactId>
    <version>3.7.0</version>
</dependency>
----

[#bundle-paths]
== Bundle Paths

After the bundling is done, the bundle files are served under `/static/bundle/...`.

In production, it is a good practise to have a hash inserted in the scripts and styles file names (E.g.: `main-XKHKUJNQ.js`) to differentiate builds (make them static). This way they can be cached without a risk of missing the most recent builds.

In the Web Bundler, we also do it in dev mode, this way the app is as close as possible to production. You won't have surprise when deploying a new version of your application.

To make it easy there are several ways to resolve the bundle files public paths from the templates and the code.

[#bundle-tag]
=== {#bundle /} tag

From any Qute template you can use the `{#bundle /}` tag. examples:

[source,html]
----
{#bundle /}
Output:
<script type="text/javascript" src="/static/bundle/main-[hash].js"></script>
<link rel="stylesheet" media="screen" href="/static/bundle/main-[hash].css">

{#bundle key="components"/}
Output:
<script type="text/javascript" src="/static/bundle/components-[hash].js"></script>
<link rel="stylesheet" media="screen" href="/static/bundle/components-[hash].css">

{#bundle tag="script"/}
Output:
<script type="text/javascript" src="/static/bundle/main-[hash].js"></script>

{#bundle tag="style"/}
Output:
<link rel="stylesheet" media="screen" href="/static/bundle/main-[hash].css">

{#bundle key="components" tag="script"/}
Output:
<script type="text/javascript" src="/static/bundle/components-[hash].js"></script>

----

=== Inject `Bundle` bean

This bean can be injected in the code:

[source,java]
----
@Inject
Bundle bundle;

...

System.out.println(bundle.script("main"));
System.out.println(bundle.style("main"));
----


or in a Qute template:
[source,html]
----
{inject:bundle.script("main")}
{inject:bundle.style("main")}
----
