= Quarkus image:logo.svg[width=25em] Web Bundler - Advanced Guides

include::./includes/attributes.adoc[]

== Web Root

The Web Root is `src/main/resources/web`, this is where the Web Bundler will look for stuff to bundle and serve.

== Public

Files in `src/main/resources/web/public` will be served statically.

== Bundling

=== Presets

The Web Bundler is pre-configured with presets to make it easy to use out of the box.

==== App

Directory `src/main/resources/web/app` is destined to contain the scripts and styles for your app.

[#server-side-web-components]
==== Server Side Web Components (Qute)

This is not always needed but if you need to add specific script and/or style to your {quarkus-guides-url}/qute-reference#user_tags[Qute tags] (Server Side Web Components). This preset will help you do it elegantly.

By convention, your component will be defined in `src/main/resources/web/components/[name]/[name].js,ts,css,scss,html`. The scripts and styles will be bundled, the html template will be usable as a {quarkus-guides-url}/qute-reference#user_tags[Qute tag].

This way all your components scripts/styles will be bundled and you tags will be available in your templates.

=== Importing Web Dependencies

Once added in the pom.xml, the web dependencies can be imported and used with the ES import syntax, they will automatically be bundled.

NOTE: Currently Web Dependencies need to be imported in order to be bundled.

.web/app/script.js
[source,javascript]
----
import $ from 'jquery';
import 'bootstrap/dist/css/bootstrap.css';

$('.hello').innerText('Hello');
----

Styles can be also be imported from a scss file:

.web/app/style.scss
[source,scss]
----
@import "bootstrap/dist/css/bootstrap.css";
----

WARNING: It is currently not possible to import `scss` from the dependencies (https://github.com/quarkiverse/quarkus-web-bundler/issues/58[more info]).

=== What is bundled

The Web Bundler will automatically generate an index from all the scripts and styles found in the bundle directory.

Alternatively, you can provide an index `index.js,ts,jsx,tsx` and manually import what's needed. Example:

.index.js
[source,javascript]
----
import './my-script.js'
import './my-style.scss'
----

NOTE: You can import and use fonts and images from your scripts and styles (svg, gif, png, jpg, woff, woff2, ttf, eot).

=== Split the bundle

The Web Bundler can be configured to split the resulting bundle. This is perfect if you create an app with different pages using different scripts, libraries and styles.

Shared code is split off into a separate file. That way if the user first browses to one page and then to another page, they don't have to download all the JavaScript for the second page from scratch if the shared part has already been downloaded and cached by their browser. The name of the shared code is `chunk`.

By default the Web Bundler will **NOT** split the code and bundle all into `main`. You can configure splitting in the configuration:

.application.properties
[source,properties]
----
quarkus.web-bundler.bundle.page-1=true // <1>
quarkus.web-bundler.bundle.page-2=true // <2>
----
<1> Bundle `src/main/resources/web/page-1/...`
<2> Bundle `src/main/resources/web/page-2/...`

You may also split the bundle for the `app` and the `component` presets (by default they will be bundled together in `main`):
.application.properties
[source,properties]
----
quarkus.web-bundler.presets.app.key=app // <1>
quarkus.web-bundler.presets.components.key=components // <2>
----
<1> The app will be bundled in `app-[hash].js`
<2> The components will be bundled in `components-[hash].js`

=== SCSS, SASS

You can use scss or sass files out of the box. Local import are supported. Importing partials is also supported begin with `_` (as in `_code.scss` imported with `@import 'code';`).

WARNING: It is currently not possible to import `scss` from the dependencies (https://github.com/quarkiverse/quarkus-web-bundler/issues/58[more info]).

[#web-dependencies]
== Web Dependencies

The Web Bundler is integrated with NPM dependencies through <<mvnpm>> (default) or <<webjars>>.
Once added in the pom.xml the dependencies are directly available through import from the scripts and styles.

[#mvnpm]
=== MVNPM (default)

mvnpm (Maven NPM) is a maven repository facade on top of the NPM Registry.

If configured with the mvnpm repository, when requesting a dependency, it will inspect the registry to see if it exists and if it does, convert it to a Maven dependency and publish it to Maven Central.

NOTE: You can also use the mvnpm.org website to synchronize new versions with Maven Central and avoid the need to add the mvnpm repository to the pom.xml.

WARNING: **Synchronisation with Maven Central is temporarily disabled**. It will be up again soon. Until then use the mvnpm repo.

Add web dependencies (and optionally the mvnpm repo) to your pom.xml:

.pom.xml
[source,xml]
----
...
<dependencies>
    ...
    <dependency>
        <groupId>org.mvnpm</groupId> // <1>
        <artifactId>jquery</artifactId> // <2>
        <version>3.7.0</version> // <3>
    </dependency>
</dependencies>
<repositories>
    <repository>
      <id>central</id>
      <name>central</name>
      <url>https://repo.maven.apache.org/maven2</url>
    </repository>
    <repository> // <4>
      <id>mvnpm.org</id>
      <name>mvnpm</name>
      <url>https://repo.mvnpm.org/maven2</url>
    </repository>
</repositories>
...
----

<1> use `org.mvnpm` or `org.mvnpm.at.something` for `@something/dep`
<2> All dependencies published on NPM are available
<3> Any https://www.npmjs.com/package/jquery?activeTab=versions[published NPM version] for your dependency
<4> Add mvnpm repository (Maven Central is also added for priority)

[#webjars]
=== WebJars

NOTE: Adding new dependencies or recent versions has to be done manually from their website.

WebJars are client-side web libraries (e.g. jQuery & Bootstrap) packaged into JAR (Java Archive) files. You can browse the repository from https://www.webjars.org/[the website, window="_blank"].

.application.properties
[source,properties]
----
quarkus.web-bundler.dependencies.type=webjars
----

.pom.xml
[source,xml]
----
<dependency>
    <groupId>org.webjars.npm</groupId>
    <artifactId>jquery</artifactId>
    <version>3.7.0</version>
</dependency>
----

[#bundled-paths]
== Bundled Paths

In production, it is a good practise to have a hash inserted in the scripts and styles file names (E.g.: `main-XKHKUJNQ.js`) to differentiate builds. This way they can be cached without a risk of missing the most recent builds.

In the Web Bundler, we also do it in dev mode, this way the app is as close as possible to production. You won't have surprise when deploying a new version of your application.

To make it easy there are several ways to resolve the bundled public paths from the templates and the code.

[#bundle-tag]
=== {#bundle /} tag

From any Qute template you can use the `{#bundle /}` tag. examples:

[source,html]
----
{#bundle /}
Output:
<script type="text/javascript" src="/static/main-[hash].js"></script>
<link rel="stylesheet" media="screen" href="/static/main-[hash].css">

{#bundle key="components"/}
Output:
<script type="text/javascript" src="/static/components-[hash].js"></script>
<link rel="stylesheet" media="screen" href="/static/components-[hash].css">

{#bundle tag="script"/}
Output:
<script type="text/javascript" src="/static/main-[hash].js"></script>

{#bundle tag="style"/}
Output:
<link rel="stylesheet" media="screen" href="/static/main-[hash].css">

{#bundle key="components" tag="script"/}
Output:
<script type="text/javascript" src="/static/components-[hash].js"></script>

----

=== Inject `Bundled` bean

This bean can be injected in the code:

[source,java]
----
@Inject
Bundled bundled;

...

System.out.println(bundled.script("main"));
System.out.println(bundled.style("main"));
----


or in a Qute template:
[source,html]
----
{inject:bundled.script("main")}
{inject:bundled.style("main")}
----
