= Quarkus image:logo.svg[width=25em] Web Bundler - Getting Started

include::./includes/attributes.adoc[]

Create full-stack web apps and components with this Quarkus extension. It offers zero-configuration bundling and minification (with source-map) for your web app scripts (JS, JSX, TS, TSX), dependencies (jQuery, htmx, Bootstrap, Lit etc.), and styles (CSS, SCSS, SASS).

No need to install NodeJs, it relies on a Java wrapped version of https://esbuild.github.io/[esbuild, window="_blank"] to bundle scripts (js, ts, jsx, tsx) and styles (css, scss, sass) and make them easily available in the templates.

* [*] Production build
* [*] Awesome Dev experience
* [*] Integrated with NPM dependencies through https://mvnpm.org[mvnpm, window="_blank"] or https://www.webjars.org/[webjars, window="_blank"].
* [*] Server Side Web Components (Qute template + Script + Style)

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.web-bundler:quarkus-web-bundler` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.web-bundler</groupId>
    <artifactId>quarkus-web-bundler</artifactId>
    <version>{project-version}</version>
</dependency>
----

== Usage

Add you web resources in `src/main/resources/web`:

* `app/**/*.js,ts,jsx,tsx,css,scss,sass`: app scripts, styles and assets
* `components/[my-comp]/[my-comp].js,ts,css,scss,html`: server side web-component
* `public/`: public static files

Add xref:advanced-guides.adoc#[Web Dependencies] and import them from your scripts and styles.

Install the bundle in your index.html template:

[source,html]
----
<html>
<head>
  ...
  {#bundle /}
</head>
</html>
----
Will compile into something looking like this:

[source,html]
----
<html>
<head>
      ...
      <script type="text/javascript" src="/static/main-XKHKUJNQ.js"></script>
      <link rel="stylesheet" media="screen" href="/static/main-TLNDARM3.css">
</head>
</html>
----

You are all set, enjoy!

NOTE: By default `{#bundle /}` inserts both script and style tags for `main`, this is xref:advanced-guides.adoc#bundle-tag[configurable].
