= Quarkus image:logo.svg[width=25em] Web Bundler - Getting Started

include::./includes/attributes.adoc[]

Create full-stack web apps and components with this Quarkus extension. It offers zero-configuration bundling and minification (with source-map) for your web app scripts (JS, JSX, TS, TSX), dependencies (jQuery, htmx, Bootstrap, Lit etc.), and styles (CSS, SCSS, SASS).

No need to install NodeJs, it relies on a Java wrapped version of https://esbuild.github.io/[esbuild, window="_blank"] to bundle scripts (js, ts, jsx, tsx) and styles (css, scss, sass) and make them easily available in the templates.

* [*] Easy to set up
* [*] Production build
* [*] Awesome Dev experience
* [*] Integrated with NPM dependencies through xref:advanced-guides.adoc#mvnpm[mvnpm] or xref:advanced-guides.adoc#webjars[WebJars].
* [*] Server Side Web Components (Qute template + Script + Style)

NOTE: The Web Bundler has been pre-configured to reduce the complexity of web bundling. You don't need to know all the concepts of web bundling (entry-points, loaders, ...) to use this extension, it has been pre-configured with sensible defaults that you may change if needed.

== Installation

If you want to use this extension, you need to add the `io.quarkiverse.web-bundler:quarkus-web-bundler` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.web-bundler</groupId>
    <artifactId>quarkus-web-bundler</artifactId>
    <version>{project-version}</version>
</dependency>
----

== Usage

Add your web resources in `src/main/resources/web`:

* `app/&#42;&#42;`: App scripts (js, ts, jsx, tsx, ...), styles (css, scss, sass) and assets (svg, jpg, gif, png, ...), to be *bundled* and served under http://localhost:8080/static/bundle/
* `static/&#42;&#42;`: Any static file to be *served* without change under http://localhost:8080/static/

Add xref:advanced-guides.adoc#web-dependencies[Web Dependencies] and import them from your scripts and styles:

.web/app/script.js
[source,javascript]
----
import $ from 'jquery';
import 'bootstrap/dist/css/bootstrap.css';

$('.hello').innerText('Hello');
----

Install the bundle in your index.html template:

[source,html]
----
<html>
<head>
  ...
  {#bundle /}
</head>
</html>
----
Will compile into something looking like this:

[source,html]
----
<html>
<head>
      ...
      <script type="text/javascript" src="/static/main-XKHKUJNQ.js"></script>
      <link rel="stylesheet" media="screen" href="/static/main-TLNDARM3.css">
</head>
</html>
----

You are all set, enjoy!

NOTE: By default `{#bundle /}` inserts both script and style tags for `main`, this is xref:advanced-guides.adoc#bundle-tag[configurable].
